apiVersion: v1
kind: Service
metadata:
  name: tempconv-frontend
  namespace: default
  labels:
    app: tempconv-frontend
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  selector:
    app: tempconv-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
